name: Test Dependency Graph - Dispatch

on:
  workflow_dispatch:
    inputs:
      os:
        type: choice
        description: OS
        options:
          - ubuntu-latest
          - macos-latest
          - windows-latest
      swift-version:
        type: choice
        description: Swift Version
        options:
          - '5.9'
          - '5.8'
          - '5.7'
          - '5.6'
          - '5.5'
          - '5.4'
          - '5.3'
          - '5.2'
          - '5.1'
          - '5.0'

jobs:
  test-dependants:
    strategy:
      fail-fast: false
      matrix:
        provider:
          - swift-libp2p/swift-cid
    runs-on: ${{ github.event.inputs.os }}
    steps:
      - name: Dump Repo Name
        env:
          REPO_NAME: ${{ github.event.repository.name }}
        run: echo "$REPO_NAME"
      - name: Setup swift
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: '${{ github.event.inputs.swift-version }}'
      - name: Check out swift-multihash
        uses: actions/checkout@v4
        with:
          path: swift-multihash
      - name: Check out provider
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.provider }}
          path: provider
          ref: ${{ matrix.ref }}
      - name: Use local swift-multihash
        run: swift package --package-path ./provider edit swift-multihash --path ./swift-multihash
      - name: Run tests
        env:
          SWIFT_DETERMINISTIC_HASHING: 1
        run: swift test --package-path ./provider
